import tkinter as tk
def change():
    btn.cofig(background='green')
win=tk.Tk()
lb1=tk.Label(win,text='user')
en1=tk.Entry(win)
a=en1.get()
lb2=tk.Label(win,text='pass')
en2=tk.Entry(win)
b=en2.get()
btn=tk.Button(win,text='click here',command=change)
lb1.pack()
en1.pack()
lb2.pack()
en2.pack()
btn.pack()
win.mainloop()
