import tkinter as tk
win=tk.Tk()
lb1=tk.Label(win,text='user')
en1=tk.entry(win)
lb2=tk.Label(win,text='pass')
en2=tk.entry(win)
btn=tk.Button(win,text='')
lb1.pack()
en1.pack()
lb2.pack()
en2.pack()
btn.pack()
win.mainloop()
